services:
  # アプリケーションサービス
  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.dev}
    environment:
      # ${XXX:-hoge}記法の右辺はデフォルト値設定
      NODE_ENV: ${NODE_ENV:-development}
    command: bun ${APP_COMMAND:-dev}
    ports:
      - 4001:4001
      - 9229:9229
    # Docker Compose Watch設定
    develop:
      watch:
        # ソースコード変更時の自動リロード
        - path: ./src
          action: sync
          target: /usr/src/app/src
        # package.jsonの変更時は依存関係を更新
        - path: ./package.json
          action: rebuild
