# 基本設定
x-app-common: &app-common
  build:
    context: .
  ports:
    - 4001:4001
  volumes:
    - .:/usr/src/app
    - node_modules:/usr/src/app/node_modules

services:
  # アプリケーションサービス
  app:
    <<: *app-common
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.dev}
    environment:
      # ${XXX:-hoge}記法の右辺はデフォルト値設定
      NODE_ENV: ${NODE_ENV:-development}
    command: yarn ${APP_COMMAND:-dev}

volumes:
  node_modules:
