# syntax=docker/dockerfile:1

FROM oven/bun:1 AS builder

# 本番ビルド環境設定
ENV NODE_ENV=production

WORKDIR /usr/src/app

# ソースコードのコピーとビルド
COPY . .
RUN bun install --production
RUN bun run build

# 本番環境用イメージ
FROM oven/bun:1-slim

ENV NODE_ENV=production

WORKDIR /usr/src/app

# 必要なファイルのみコピー
COPY --from=builder /usr/src/app/dist ./dist

# アプリケーションポート
EXPOSE 4001

# 本番用起動コマンド
CMD ["bun", "start"]
