# syntax=docker/dockerfile:1

FROM oven/bun:1 AS base

# 開発環境設定
ENV NODE_ENV=development

WORKDIR /usr/src/app

# ソースファイルのコピー
COPY . .
RUN bun install

# アプリケーションポート
EXPOSE 4001
EXPOSE 9229

# 開発用コマンド
CMD ["bun", "dev"]
